atoms/input first commit
yuta-frontend/gottyan-frontend-basic-2022-todoapp pull request #6
Opened 2023-03-31 14:10 UTC by yuta-frontend

レビューお願いします

2023-03-31 14:18 UTC, yuta-frontend commented
frontendbasic最終課題のreactの説明がよくわからなかったので、自分の知識でできる限りやりました。

2023-03-31 22:37 UTC, haruchu reviewed
この課題で行うことはまとめると以下のような感じです。
- Enter押した時、Inputのfocusが外れた(他をクリックした)時に、propsで受け取った関数を実行。今回で言うと入力された内容をコンソール表示
- 同じくpropsでデフォルト値を取得して、Inputの内容を初期化（useEffectで最初のみ一度だけ初期化するイメージ）
- 初期化と同時にInputが自動でfocusされる
<img width="791" alt="スクリーンショット 2023-04-01 7 36 02" src="https://user-images.githubusercontent.com/66406382/229244614-3529f1a5-ccc8-4741-bd73-1a3547b22fc8.png">

2023-03-31 22:37 UTC, haruchu commented on src/components/Atoms/Input/story.jsx
> +  onClick: () => console.log("clicked"),
ここで定義しているonClickという関数は、作成したコンポーネントでpropsとして受け取らないと機能しません！
[公式ドキュメントpropsの部分](https://react.dev/learn/passing-props-to-a-component)

2023-03-31 22:37 UTC, haruchu commented on src/components/Atoms/Input/index.jsx
> +const Title = () => {
コンポーネント名は`Input`の間違いかと

2023-04-07 14:45 UTC, KEISUKE0293 reviewed
figmaと見比べてデザインが少し異なっている部分があるので直しておきましょう！（外枠や文字のフォントなど）

2023-04-07 23:53 UTC, higashiji2000 requested changes

2023-04-07 23:53 UTC, higashiji2000 commented on src/components/Atoms/Input/story.jsx
> +;
```suggestion
 Default.args = {
   onEditComplete: (value) => console.log("edit completed: ", value),
 };
```
こんな感じで入力内容がコンソールに出力されるようにしてください！

2023-04-07 23:53 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +      if (e.key == "Enter") {
```suggestion
      if (e.key === "Enter") {
```
可能な限り厳密等価演算子を使っていきましょう。
参考：https://zenn.dev/bokutano26/articles/442f11f4ec69bf

2023-04-07 23:53 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +    ref.current.onblur = (e) => onEditComplete(e.current.value);
![image](https://user-images.githubusercontent.com/83479175/230692995-ea05073b-4d62-41ee-b316-48855b74268d.png)

> Uncaught TypeError: Cannot read properties of undefined (reading 'value')

編集後このようなエラーが出ています。
```suggestion
    ref.current.onblur = (e) => onEditComplete(e.target.value);
```
これは `e.current` が `undefined` であることを示しています。
`ref` では `current` を介してDOMを取得していましたが、イベントオブジェクトにおいては、 `target` にDOM(`input`)が入っていますので、上のように修正していただければエラーが出なくなると思います。
参考：https://qiita.com/kuutarou/items/a6f61d1bbc50378034af

2023-04-07 23:53 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +        onEditComplete(e.current.value);
```suggestion
        onEditComplete(e.target.value);
```
こちらも同様です。

2023-04-08 12:59 UTC, MoAI522 approved these changes
LGTM

2023-04-08 12:59 UTC, merged